Feature/9
makingdevs/Advent-of-Code pull request #10
Opened 2019-04-24 15:34 UTC by EdsonSrv

Día 5 completado

2019-04-24 21:29 UTC, neodevelop requested changes
Aplicar algunos cambios por fa!

2019-04-24 21:29 UTC, neodevelop commented on Year-2015/dia05/dia_05_1.groovy
> +	for (char v: vowels){
Puedes usar un `each' por que son Collections

2019-04-24 21:29 UTC, neodevelop commented on Year-2015/dia05/dia_05_1.groovy
> +		for (int i = 0; i < st.length(); i++){
generalmente ya no usas `for` por que tienes un elemento que contabilizar

2019-04-24 21:29 UTC, neodevelop commented on Year-2015/dia05/dia_05_1.groovy
> +	total_vowels >= 3
No uses número mágicos o declarados como constantes

2019-04-24 21:29 UTC, neodevelop commented on Year-2015/dia05/dia_05_1.groovy
> +	for(int i = 0; i < st.length(); i++)
creo que hay mucha complejidad ciclomática aquí

2019-04-24 21:29 UTC, neodevelop commented on Year-2015/dia05/dia_05_1.groovy
> +def isContainRestrictedLetters(String st){
tal vez usar un switch

2019-04-24 21:29 UTC, neodevelop commented on Year-2015/dia05/dia_05_1.groovy
> +f.eachLine() {
muy bien! `eachLine`

2019-04-24 21:29 UTC, neodevelop commented on Year-2015/dia05/dia_05_2.groovy
> +def propertie1(String st){
Nombres más descriptivos por favor

2019-04-24 21:29 UTC, neodevelop commented on Year-2015/dia05/dia_05_2.groovy
> +	for (int i = 0; i < st.length()-1; i++)
¿es necesaria esta complejidad?
Es pregunta...

2019-04-24 21:31 UTC, neodevelop submitted a review, later dismissed
Aplicar algunos cambios por fa!

2019-04-29 16:11 UTC, EdsonSrv commented on Year-2015/dia05/dia_05_2.groovy
> +	for (int i = 0; i < st.length()-1; i++)
No

2019-04-29 16:39 UTC, EdsonSrv commented on Year-2015/dia05/dia_05_1.groovy
> +	total_vowels >= 3
No entendí :S

2019-12-09 19:22 UTC, merged